# Generated by Django 5.0.4 on 2024-10-14 00:24

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='', validators=[Petstagram.photos.validators.FileSizeValidator(5)]),
        ),
    ]
