# Generated by Django 5.0.4 on 2024-10-14 00:32

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='mediafiles', validators=[Petstagram.photos.validators.FileSizeValidator(5)]),
        ),
    ]
