# Generated by Django 5.0.4 on 2024-10-21 02:14

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='', validators=[Petstagram.photos.validators.FileSizeValidator(5)]),
        ),
    ]
