# Generated by Django 5.0.4 on 2024-10-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('pets', '0001_initial'), ('pets', '0002_alter_pet_slug'), ('pets', '0003_alter_pet_slug'), ('pets', '0004_alter_pet_personal_photo'), ('pets', '0005_alter_pet_personal_photo')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('personal_photo', models.URLField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
            ],
        ),
    ]
