# Generated by Django 5.0.4 on 2024-10-14 00:23

import Petstagram.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='personal_photo',
            field=models.URLField(validators=[Petstagram.photos.validators.FileSizeValidator(5)]),
        ),
    ]
