# Generated by Django 5.0.4 on 2024-10-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_personal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='personal_photo',
            field=models.URLField(),
        ),
    ]
